### ISSUE TITLE
Awesome Project ! 

### ISSUE THREAD

**Issue by unuigbee** [mrcreatoor/MagicKit#1]
Hi, I've recently been trying to find a way integrate some cool GLTransitions into my project as a swift package dependency but couldn't find a way to do this successfully. You've saved me a lot of time. Thanks.

I was able to easily create some looping transition with it. A gist if anyone is interested: https://gist.github.com/unuigbee/a12ed61a84d862ad5462f796c9c42e42

https://user-images.githubusercontent.com/6902308/236838299-92ace654-34c4-4515-9cba-45e395142253.mp4

**Comment by mrcreatoor** [comment]
You're welcome! I'm glad that I could help you save some time. It's always helpful to see examples of how others have used this library.
